# Generated by Django 5.1.4 on 2025-02-13 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_stress', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
